apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: sample-notebook
spec:
  template:
    spec:
      containers:
        - name: notebook
          image: kubeflownotebookswg/jupyter-tensorflow-full:v1.7.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 500m
              memory: 1Gi