apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  annotations:
  labels:
    access-ml-pipleine: "true"
    app: sample-notebook
  name: sample-notebook
spec:
  template:
    spec:
      containers:
      - name: notebook
        image: kubeflownotebookswg/jupyter-pytorch-full:v1.8.0-rc.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
