name: On Pull Request

on:
  pull_request:

jobs:
  populate-labels:
    name: Populate labels
    if: github.base_ref == 'main' && (github.event.action == 'opened' || github.event.action == 'reopened')
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/populate-labels.yaml@main
    secrets: inherit
    with:
      track_file_path: ".github/automatic_backport_tracks.yaml"
      label_prefix: "backport "
