# reusable workflow triggered by other actions
name: Publish

on:
  workflow_call:
    secrets:
      charmcraft-credentials:
        required: true

jobs:

  publish-charm:
    name: Publish Charm
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        charm:
          - jupyter-controller
          - jupyter-ui
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Select charmhub channel
        uses: canonical/charming-actions/channel@1.0.3
        id: channel
      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@1.0.3
        with:
          credentials: ${{ secrets.charmcraft-credentials }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          charm-path: charms/${{ matrix.charm }}
          channel: ${{ steps.channel.outputs.name }}
          tag-prefix: ${{ matrix.charm }}
